baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'docura'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    languageCode = "en-US"
    contentDir = "content/en"
    title = "Pirateship"
    [languages.en.params]
      description = "Consensus Protocol for (Mostly) Trusted Execution Environments"

[menu]
  [[menu.main]]
    url = "/"
    name = "Home"
    identifier = "home"
    pre = "<i class='icon icon-home'></i>"
    weight = 1

  [[menu.main]]
    url = "/docs"
    name = "Documentation"
    identifier = "docs"
    pre = "<i class='icon icon-book'></i>"
    weight = 2

  [[menu.main]]
    url = "/docs/presentation"
    name = "Talks and Slides"
    identifier = "talks"
    pre = "<i class='icon icon-youtube'></i>"
    weight = 2


[params]

[params.author]
name = "Shubham Mishra"
url = "https://grapheo12.in"

[params.years]
start = 2024
present = 2025

[params.home]

repository = "PirateshipOrg/pirateship"

